### ISSUE TITLE
undefined symbol: limit_needed

### ISSUE THREAD

**Issue by xuhongmeng** [alitrack/duckdb_fdw#1]
create extension duckdb_fdw
get error:
undefined symbol: limit_needed

**Comment by alitrack** [comment]
Please let me know the PG version you used and the OS environment,  thanks in advance.

**Comment by xuhongmeng** [comment]
PG version :10.1
OS: centos 7.4
where i search  'limit_needed' in ducked_fdw project,  that is in file  duckdb_fdw.c, but not found the define。

**Comment by alitrack** [comment]
make sure you have installed postgresql-server-dev-10

limit_needed is defined in 

/usr/include/postgresql/10/server/optimizer/planner.h:extern bool limit_needed(Query *parse);
