### ISSUE TITLE
Read only foreign server support

### ISSUE THREAD

**Issue by j4david** [alitrack/duckdb_fdw#10]
Please allow read-only connections again.

The latest versions of duckdb_fdw do not support read-only accesses and there are problems when querying from more than one session, or when querying foreign tables via Power BI.

I have managed to compile in read-only mode with this code modification, but it is somewhat static.

```
--- a/connection.c
+++ b/connection.c
@@ -210,7 +210,7 @@ sqlite_make_new_connection(ConnCacheEntry *entry, ForeignServer *server)
                // }
        }

-       rc = sqlite3_open_v2(dbpath, &entry->conn, DUCKDB_UNSIGNED_EXTENSIONS, NULL);
+       rc = sqlite3_open_v2(dbpath, &entry->conn, DUCKDB_UNSIGNED_EXTENSIONS  | SQLITE_OPEN_READONLY  , NULL);
        // rc = sqlite3_open_v2(dbpath, &entry->conn,flags, NULL);
```

Please consider including a foreign server option to enable it, as it was last year.

Thank you for writing this software.

Best regards.

**Comment by alitrack** [comment]
thanks 
fix the bug.
btw, would you mind share about how to use duckdb_fdw with Power BI, thanks in advance.

**Comment by j4david** [comment]
Thank you

It didn't work. It failed with this error:

```
create extension duckdb_fdw;

create server duckdb_srv foreign data wrapper duckdb_fdw options (database '/tmp/db.duckdb', read_only 'true');
--ERROR:  invalid option "read_only"
--HINT:  Valid options in this context are: database, truncatable, keep_connections, batch_size

create server duckdb_srv foreign data wrapper duckdb_fdw options (database '/tmp/db.duckdb'); -- OK
grant usage on foreign server duckdb_srv to dev;
```

I add this line in options.c and it works:

```
diff --git a/option.c b/option.c
index 90d06de..1a0091d 100644
--- a/option.c
+++ b/option.c
@@ -68,6 +68,7 @@ static struct SqliteFdwOption valid_options[] =
        /* batch_size is available on both server and table */
        {"batch_size", ForeignServerRelationId},
        {"batch_size", ForeignTableRelationId},
+       {"read_only", ForeignServerRelationId},
        /* Sentinel */
        {NULL, InvalidOid}
 };
```

I am experimenting with Power BI and DuckDB. DuckDB has an ODBC driver that allows Power BI to connect, but I think it has several problems. It does not detect the data types on the Power BI side and also does not allow concurrent connections, so there are errors loading data from Power BI.

Your extension is more comfortable for me to connect to Power BI with DuckDB, because it allows me to detect the data types and now multiple connections. Basically, what I do is to load duckdb_fdw and import several DuckDB files with all their tables (doing a foreign schema import). Then in Power BI, I just have to establish a connection to Postgresql. It is really very useful for me. So thank you very much.

Best regards.

**Comment by alitrack** [comment]
thanks
I forgot committing   `option.c`.

and thanks for your sharing.
