### ISSUE TITLE
服务器异常中止，连接不上服务

### ISSUE THREAD

**Issue by starlet-lxxx** [alitrack/duckdb_fdw#17]
在使用过程中遇到了连接不上的报错，请问是哪里有问题吗，具体过程如下：

postgres=# CREATE EXTENSION duckdb_fdw;
postgres=# CREATE SERVER duckdb_server FOREIGN DATA WRAPPER duckdb_fdw OPTIONS (database '/opt/fdw/data/data');
postgres=# IMPORT FOREIGN SCHEMA public FROM SERVER duckdb_server INTO public;
server closed the connection unexpectedly
        This probably means the server terminated abnormally
        before or while processing the request.
The connection to the server was lost. Attempting reset: Failed.
!>

duckdb版本为：v0.6.1
pgsql版本为 ：PostgreSQL 12.15 (Ubuntu 12.15-0ubuntu0.20.04.1) on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0, 64-bit
创建的'/opt/fdw/data/data'数据库是用v0.6.1创建的

**Comment by alitrack** [comment]
Postgres 服务器用户是否有权限访问该目录？'/opt/fdw/data/data'
