### ISSUE TITLE
Compatibility with MotherDuck connection string

### ISSUE THREAD

**Issue by williamong68** [alitrack/duckdb_fdw#19]
I see that this current repo works with local duckdb server. Is there on the roadmap any plans for a connection to a duckdb server that is hosted on Motherduck using the connection string?

**Comment by alitrack** [comment]
does there exist a connection string on Motherduck?

**Comment by williamong68** [comment]
Yes, there is a share option that I saw that when clicked, would give a connection url.

**Comment by alitrack** [comment]
have you successfully attached it to your local DuckDB?
I tried on My mac m2, got an error
```
Running query in 'duckdb:///'
(duckdb.InvalidInputException) Invalid Input Error: Initialization function "motherduck_init" from file "/Users/m2max/.duckdb/extensions/v0.8.1/osx_arm64/motherduck.duckdb_extension" threw an exception: "IO Error: Failed to download "http://api.motherduck.com/extension_version". Status code "403": Success" [SQL: ATTACH 'md:_share/my_db/<string_of_generated_numbers_and_digits>'] (Background on this error at: https://sqlalche.me/e/14/f405)
```

**Comment by alitrack** [comment]
@williamong68  here is a [Chinese article](https://mp.weixin.qq.com/s?__biz=MzU1NTg2ODQ5Nw==&mid=2247488591&idx=1&sn=c998bf0aef676949ae8e03a84c0a9d7f&chksm=fbcc9c71ccbb156731098a1ced02f1a6b7bd90c7cf5ea7af58d79c8a0cc2a325ef282f8d3158&token=1556061759&lang=zh_CN#rd) about how to connect with MotherDuck through duckdb_fdw
