### ISSUE TITLE
array_agg is performed by PostgreSQL not by duckdb

### ISSUE THREAD

**Issue by ahuarte47** [alitrack/duckdb_fdw#20]
Hi, first of all, thank you very much for developing this amazing tool!

I am facing one issue executing a query that includes the `array_agg` function.

Without "array_agg" query plan looks great:
![image](https://github.com/alitrack/duckdb_fdw/assets/5576272/9ed39d1a-5e4e-45a8-b87e-2ecfdb67aa91)
![image](https://github.com/alitrack/duckdb_fdw/assets/5576272/b12ddc32-2721-4b1a-a1ed-4434ecdea837)

But when I add `array_agg` function, it is not included in the query to run in Duckdb, but it is perfomed by PostgreSQL:
![image](https://github.com/alitrack/duckdb_fdw/assets/5576272/362b9701-00d8-44c2-83dc-607556227334)
![image](https://github.com/alitrack/duckdb_fdw/assets/5576272/25bc56f1-662c-469b-9866-60b5a1a8d169)

The performance is very much worse, please, what I am doing wrong?, is there an issue?
Thanks in advance

**Comment by ahuarte47** [comment]
Maybe this [filter](https://github.com/alitrack/duckdb_fdw/blob/main/deparse.c#L836) of functions is the key?

**Comment by ahuarte47** [comment]
I did a proof, adding "array_aggr" to that if, I am getting an error...

ERROR:  Missing "]" after array dimensions.malformed array literal: "[0.0955189977798119, 0.0955189812229662]" 

Unfortunatelly I am not able to debug your code to figure what is wrong

**Comment by ahuarte47** [comment]
I propose this [PR](https://github.com/alitrack/duckdb_fdw/pull/21) that resolve this issue

**Comment by alitrack** [comment]
sorry for the delay, and let me check it.

**Comment by ahuarte47** [comment]
Thank you very much @alitrack for your review

**Comment by ahuarte47** [comment]
I am closing this ticket, code got merged. Tahnks @alitrack
