### ISSUE TITLE
Undefined symbol linking DuckDB 0.9.2

### ISSUE THREAD

**Issue by ahuarte47** [alitrack/duckdb_fdw#25]
I am getting undefined symbol when running in Ubuntu 22.04 the DuckDB FDW linked with DuckDB v0.9.2. 
It runs properly with DuckDB v0.8.1.

Error:
`could not load library "/duckdb_fdw.so": /duckdb_fdw.so: undefined symbol: _ZN6duckdb13KeywordHelper9IsKeywordERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE`

Same issue in PostgreSQL 15.5 or 16.1.

Please, do you know what is the problem?

**Comment by alitrack** [comment]
try this [docker](https://github.com/alitrack/duckdb_fdw_docker) and let me know if you have any question.

**Comment by ahuarte47** [comment]
Thanks @alitrack, using this image I am getting same error.

`ERROR:  could not load library "/usr/lib/postgresql/16/lib/duckdb_fdw.so": /usr/lib/postgresql/16/lib/duckdb_fdw.so: undefined symbol: _ZN6duckdb13KeywordHelper9IsKeywordERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE
`

**Comment by alitrack** [comment]
updated Makefile, and try again.

**Comment by ahuarte47** [comment]
Thanks!!! it works now!
