### ISSUE TITLE
Enable concurrent connection

### ISSUE THREAD

**Issue by nestarz** [alitrack/duckdb_fdw#4]
Hello @alitrack,

Every time there is more than one connection I get the following error:
ERROR:  failed to open SQLite DB. rc=1 path=/var/lib/postgresql/database.duckdb

Do you know how i can set postgres to behave in read only mode when making a connection to the duckdb database so it can allow multiple connections ?

See https://github.com/cwida/duckdb/issues/77

**Comment by nestarz** [comment]
Following https://github.com/cwida/duckdb/issues/1343 it seems i need to make a connection as read-only but is this something to be done in postgres or inside the wrapper code ?

Thanks

**Comment by alitrack** [comment]
fixed
