### ISSUE TITLE
Add license

### ISSUE THREAD

**Issue by jhult** [alitrack/duckdb_fdw#5]
README mentions [MIT](https://spdx.org/licenses/MIT.html).

META.json mentions [PostgreSQL](https://spdx.org/licenses/PostgreSQL.html).

**Comment by alitrack** [comment]
I am not familiar with it, can I use MIT? I added a LICENSE, but not sure if correct.

**Comment by jhult** [comment]
I like the MIT license.

You should also update this line to MIT: https://github.com/alitrack/duckdb_fdw/blob/62724d27efc2a7ba65a0c40d7af5e8d34a7c42d1/META.json#L7

**Comment by alitrack** [comment]
> I like the MIT license.
> 
> You should also update this line to MIT:
> 
> https://github.com/alitrack/duckdb_fdw/blob/62724d27efc2a7ba65a0c40d7af5e8d34a7c42d1/META.json#L7

done.

**Comment by jhult** [comment]
Thanks.
