### ISSUE TITLE
support postgres 14

### ISSUE THREAD

**Issue by jarifuri** [alitrack/duckdb_fdw#6]
Hello, please do you plan to support also postgresql 14?

I already used the fdw in 13 (btw this fdw, and of course DuckDb, simplified a lot my work, so thanks a lot!), but as expected, when try to install it for 14 I got:
`Makefile:41: *** PostgreSQL  9.6, 10, 11, 12 or 13 is required to compile this extension.  `

**Comment by alitrack** [comment]
done, but without complete test.
