### ISSUE TITLE
Dose duckdb_fdw install on windows?

### ISSUE THREAD

**Issue by hengaini2055** [alitrack/duckdb_fdw#9]
What about "Add a directory of pg_config to PATH"? Postgresql 14 install on windows 10, and pg_config.exe is in "E:\Postgre\14\bin". I add this directory to system envirment variable PATH. Is it correct?
When I git clone https://github.com/alitrack/duckdb_fdw, and 
```
PS E:\temp\polars_20221023\duckdb_fdw> make USE_PGXS=1
process_begin: CreateProcess(NULL, uname, ...) failed.
Makefile:23: pipe: No error
Makefile:40: *** PostgreSQL 10, 11, 12, 13, 14 or 15 is required to compile this extension.  Stop.
````

**Comment by alitrack** [comment]
have not tested it on Windows, because I have no Windows PC
before `make USE_PGXS=1` make sure `pg_config` works at the same cli window.
